# Possible Issues:
#
# .gradlew permission denied:
# git update-index --chmod=+x gradlew //http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied

language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - openssl aes-256-cbc -K $encrypted_ff109aeab779_key -iv $encrypted_ff109aeab779_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
  - ./gradlew clean assemble --stacktrace
  - ./gradlew checkstyle lint --stacktrace
  - ./gradlew testReleaseUnitTest --info

after_success:
  - ./gradlew jacocoTestReleaseUnitTestReport coveralls --info

deploy:
  - provider: script
    script: ./gradlew install bintrayUpload --info
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "ilOoLdGsTdT035rhIvWX3Cxgaf2bzRSY0C8bS1huC7b1tmsJ0dkoEqKC3njvfHmvnSWtH/xhRf5OKRlwxSnNNTruJVmNYxB+YbnWZ/5geUKIOXPoMPfEDgV5mkLjVOpZ7Dpbk/DqMFI5WQj3cYaDTTY2GvWU+ugKCio6+/2eEweZwUSyCtG3vaFr9//PyvXXA49FAovog2upMN0MYGur+MilXCfYzcn8toKlMsywUzca8Mz+lC+0QWDmoehrE5vsxBpcY+GHlsgEQX57pWdL0DzD0pvvOmwrEShA4+rgBTwuvxSdgg3CJ4pAL+NO8cZ9c0vfgom0MbHzP30x1ul9F4MmOMWg0VXTSosxTXKKlCwYX4x16T9Lrybu6q4KQOX9dxCCG+aw7RxMVG9O3Pgo3oYXtzOGoX0Tg1YUsy7Y1+wJLu0ZQ2FWn6bmb6TlO23KryhhYxjN6M7UbLTGbCY9310Sdx8eAgpTHUqvhOPaY51I7v2WRgZE3CZoXYKrcKZ5WHMwDDUGp7pEVZm0r+AN6Uma3ko31teFWu1aAjYXxCE3B7b91HorB/n4jky1sN27Y5vkAWF3OheDyviiIIs6GyQJ5uaemlKT9kCKbVfSNReNgNHKeDgP4mm5/k5pCiIIafbuUkgTMzwYY6QaGSEb/vz1XJ70PvYnDUOZP/WCmik="
    file_glob: true
    file:
     - 'slf4j-timber/build/outputs/aar/*.aar'
    skip_cleanup: true
    on:
      branch: master
      tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack:
    secure: "D5qM/NEz/wjtvBo1KzJv1ioyOmvPTnm7O3sug02q8EKjVbGF4V7EBSrlRHzzZTS6sydWTr0dsU03x/G8MvCTGeKVin4XFD9RdF36H5EXt3o63ciTrpXDXcB+iBbuO4knV06gvbsMj3c9k51++p5QYXs+KRly20VQYDyfrwVOo9FTIXG7NKozFz0nypNiy+/Q0YG+2cyNZc8fvJGuqK+xn2VVqZxXi0b1mxyjuDA/o+glsr7iFT8st9uYZL4mjSJiRCZx9hF8u+CPgvWGIhtnHvu5wYujM8PPbcuyeFvYKRgGhsPV6nxXqu4ptGDE+EsuIf9adart6ETREZFbzvHAk8nzE4OdlCDU7bb0WkkH8VlYCnxiyHwHUhtr928xRHsJ8MewEZqB1pCoolaKIRVMY7W4zz0t38XvebfKHlyEZ6Fdbc9JigmGwlIr4nyVz6n/VAmR3zdL4wwCre1c7zQirnchQcTdjnkvgZ/y3gLQw6w5JN/Uqg5wsTjHsqbB7FuTwOBA1xe+Z1fBVofUsfMax/ja/b2F2TfrA/ug28QaRCjGEOeTSDaQETmy+Wy4y76daNUsWFGEid1M743iQ97ZIRGsCq//QJmLFWJd35qgeKIZeAy+FDZ27yvEShPwXKm2sIh3gRyrJDIpWZ2Is2/ITcL/5XeGSjf5MBwDSXRMB/4="
  email: false
